apiVersion: v1
kind: Service
metadata:
  name: fleetman-front-end 

spec:
  selector:
    app: front-end
  ports:
    - name: http
      port: 80
      nodePort: 30020
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway 

spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
  type: ClusterIP











