apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2